spring.application.name=ttreasurysvkg

# Server port
server.port=9014

# H2 als Derby konfigurieren
spring.datasource.url=jdbc:derby:database;create=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class=org.apache.derby.jdbc.EmbeddedDriver
spring.datasource.sqlScriptEncoding=UTF-8

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.DerbyDialect
spring.jpa.open-in-view=false

# h2
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# language properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true

logging.level.org.springframework.data=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

spring.mvc.locale=de_DE
spring.mvc.locale-resolver=fixed
